adminUser: admin

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 10Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated.observability.svc.cluster.local
        isDefault: true