apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-cpu-alert
  namespace: observability

spec:
  groups:
    - name: cpu-alerts
      rules:
        - alert: HighCPUUsage
          expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
          for: 2m

          labels:
            severity: warning

          annotations:
            summary: High CPU usage detected
            description: CPU usage is above 80%